name: Build and Deploy
on:
  push:
    branches:
      - feature/lab_final

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install Dependencies
        run: |
          npm install
            if [ $? -ne 0 ]; then
              echo "Error al construir el proyecto"
              notify:
                  - mail:
                      to: ${EMAIL_TO}
                      subject: 'Error Install Dependencies'
                      body: 'Se produjo un error en la instalaci贸n de dependencias en ${GITHUB_REPO}.'
              exit 1
            fi
            
      - name: print de repo
        run: echo "perro pepe de la suerte -> ${GITHUB_REPO}"
      
      # - name: Send Error Email - Install Dependencies
      #   if: failure()
      #   uses: actions/send-email@v1
      #   with:
      #     from: "github-actions@${GITHUB_REPO}.com"
      #     to: ${{ secrets.EMAIL_RECIPIENT }}
      #     subject: "Error en Install Dependencies"
      #     body: "Se produjo un error en la instalaci贸n de dependencias en ${GITHUB_REPO}."


      - name: Validar existecia de SonarCloud
        run: |
          if [ ! -d ~/.sonar ]; then
            echo "Dependencias de SonarCloud no encontradas. Instalando..."
            curl -sSf https://sonarcloud.io/static/cli-latest.sh | sh
            export SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
            export SONAR_HOST_URL=https://sonarcloud.io
          else
            echo "Dependencias de SonarCloud encontradas."
          fi
      
      # - name: Send Error Email - SonarCloud
      #   if: failure()
      #   uses: actions/send-email@v1
      #   with:
      #       from: "github-actions@${GITHUB_REPO}.com"
      #       to: ${{ secrets.EMAIL_RECIPIENT }}
      #       subject: "Error en prueba SAST"
      #       body: "Se produjo un error en la verificaci贸n de existencia de SonarCloud en ${GITHUB_REPO}."
        
      # - name: SonarCloud Scan #SAST
      #   uses: sonarcloud/sonarcloud-github-action@v3
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     LAB_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=labfinal-devsecops
      #       -Dsonar.organization=LabFinal_DevSecOps
      #       -Dsonar.host.url=https://sonarcloud.io
      #     working-directory: ${{ github.workspace }}
      #     timeout: 30m

      - name: Build
        run: npm run build
      
      - name: Mensaje de finalizaci贸n
        run: echo "Termino bien hasta ahora"
