name: React - Laboratorio Final
on:
  push:
    branches:
      - feat/lab_final_devsecops

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Install Dependencies
        run: npm install  

      - name: Mensaje avance
        run: echo "Instalación de dependencias V2"

