name: Build and Deploy
on:
  push:
    branches:
      - feature/lab_final

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          npm install
          if [ $? -ne 0 ]; then
            echo "Error al construir el proyecto"
            # bash./.github/workflows/send-email.sh "Error Install Dependencies" "Se produjo un error en la instalación de dependencias en ${REPO_GITHUB}."
            exit 1
           else
             echo "Instalación correcta"
            #  bash./.github/workflows/send-email.sh "Instalació Correcta" "La instación de dependencias fue ejecutada exitosamente en ${REPO_GITHUB}."
          fi

      - name: Validate SonarCloud
        run: |
          if [ ! -d ~/.sonar ]; then
            echo "Dependencias de SonarCloud no encontradas. Instalando..."
            curl -s -X POST -u "$SONAR_TOKEN:" "$SONAR_URL/api/projects/create" -d "name=$REPO&project=${GITHUB_ORG}_$REPO&organization=$SONAR_ORG&visibility=private"
            #curl -sSf https://sonarcloud.io/static/cli-latest.sh | sh
            if [ $? -ne 0 ]; then
              echo "Error al instalar SonarCloud"
              # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
              exit 1
            fi
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Build
        run: npm run build

      - name: Mensaje de finalización
        run: echo "Termino bien hasta ahora"