name: Build and Deploy
on:
  push:
    branches:
      - feature/lab_final

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/checkout@v4
        # with:
        #   sparse-checkout: .
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Install Dependencies
        run: npm install  

      - name: Validar existecia de SonarCloud
        run: |
          if [! -f sonar-project.properties ]; then
            echo "sonar-project.properties no encontrado. Creado..."
            touch sonar-project.properties
            echo "sonar.projectKey=labfinal-devsecops" >> sonar-project.properties
            echo "sonar.projectName=LabFinal_DevSecOps" >> sonar-project.properties
            echo "sonar.projectVersion=1.0" >> sonar-project.properties
            echo "sonar.sources=." >> sonar-project.properties
            echo "sonar.language=ts" >> sonar-project.properties
            echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
          fi
        
      - name: SonarCloud Scan #SAST
        uses: sonarcloud/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: npm run build
      
      - name: Mensaje de finalización
        run: echo "Termino bien hasta ahora"
