name: React - Laboratorio Final
on:
  push:
    branches:
      - feature/lab_final

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      
      - name: Install Dependencies
        run: npm install   

      - name: Build
        run: npm run build
      
      - name: Mensaje de finalización
        run: echo "Termino bien hasta ahora"
