name: Build and Deploy
on:
  push:
    branches:
      - feature/lab_final

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            java-version: '17'
            distribution: 'adopt'
      
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install
          if [ $? -ne 0 ]; then
            echo "Error al construir el proyecto"
            # bash./.github/workflows/send-email.sh "Error Install Dependencies" "Se produjo un error en la instalación de dependencias en ${REPO_GITHUB}."
            exit 1
           else
             echo "Instalación correcta"
            #  bash./.github/workflows/send-email.sh "Instalació Correcta" "La instación de dependencias fue ejecutada exitosamente en ${REPO_GITHUB}."
          fi

      - name: Validate SonarCloud
        run: |
          if [ ! -d ~/.sonar ]; then
            echo "Dependencias de SonarCloud no encontradas. Instalando..."
            curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=labfinal-devsecops' -d 'visibility=public'
            echo "Instalando..."
            if [ $? -ne 0 ]; then
              echo "Error al instalar SonarCloud"
              # bash./.github/workflows/send-email.sh "Error SonarCloud" "Se produjo un error en la instalación de SonarCloud en ${REPO_GITHUB}."
              exit 1
            fi
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Build
        run: npm run build

      - name: Mensaje de finalización
        run: echo "Termino bien hasta ahora"