name: React - Laboratorio Final
on:
  push:
    branches:
      - feature/lab_final

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout Code
      run: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: |
        npm run build